### ISSUE TITLE
Fails to build with http-enumerator >= 0.7

### ISSUE THREAD

**Issue by hvr** [bos/pronk#5]
When trying to build `pronk` with `http-enumerator-0.7.1` the compilation fails:

```
[1 of 4] Compiling Network.HTTP.LoadTest.Types ( lib/Network/HTTP/LoadTest/Types.hs, dist/build/Network/HTTP/LoadTest/Types.o )

lib/Network/HTTP/LoadTest/Types.hs:40:15:
    Not in scope: data constructor `Request'

lib/Network/HTTP/LoadTest/Types.hs:40:15:
    You cannot use `..' in a record pattern

lib/Network/HTTP/LoadTest/Types.hs:50:21:
    Not in scope: data constructor `Request'

lib/Network/HTTP/LoadTest/Types.hs:50:21:
    You cannot use `..' in a record pattern
```

This is due to an API change in `http-enumerator` (see http://hdiff.luite.com/cgit/http-enumerator/commit?id=0.7.0 ) which doesn't export the `Request` value-constructor anymore.

**Comment by ocharles** [comment]
Mostly commenting to watch this issue, as it affects me too

**Comment by jabley** [comment]
I worked around this by configuring an explicit dependency less than 0.7.0.

```
diff --git a/pronk.cabal b/pronk.cabal
index ee93fce..0af7f1b 100644
--- a/pronk.cabal
+++ b/pronk.cabal
@@ -46,7 +46,7 @@ library
     case-insensitive,
     criterion >= 0.5.1.0,
     hashable >= 1.1.2.0,
-    http-enumerator,
+    http-enumerator < 0.7.0,
     http-types,
     statistics,
     text,
```

I've not created a pull request though, since I don't know whether this is the right thing to do (I don't know haskell or cabal).

**Comment by nraychaudhuri** [comment]
Thanks a lot. It worked. Please submit your pull request because I could have saved few hours debugging the problem.

**Comment by bos** [comment]
Thanks to @hvr for the proper fix!
